# Generated by Django 4.1.7 on 2023-03-12 18:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokerSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_revealed", models.BooleanField(default=False)),
                (
                    "deck",
                    models.CharField(choices=[("tshirt", "T-shirt sizes"), ("fibonacci", "Fibonacci")], max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("is_spectator", models.BooleanField(default=False, help_text="Spectators cannot vote themselves")),
                ("is_admin", models.BooleanField(default=False, help_text="Admins can reveal and reset the votes.")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Users are active if they have an active websocket connection"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("vote", models.CharField(max_length=10, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="users", to="poker.pokersession"
                    ),
                ),
            ],
        ),
    ]
