# Generated by Django 4.1.7 on 2023-03-10 20:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_revealed", models.BooleanField(default=False)),
                (
                    "deck",
                    models.CharField(choices=[("tshirt", "T-shirt sizes"), ("fibonacci", "Fibonacci")], max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("is_spectator", models.BooleanField(default=True, help_text="Spectators cannot vote themselves")),
                ("is_admin", models.BooleanField(default=True, help_text="Admins can reveal and reset the votes.")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("vote", models.CharField(max_length=10, null=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="poker.session")),
            ],
        ),
    ]
