# Generated by Django 4.1.7 on 2023-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokersession",
            name="deck",
            field=models.CharField(
                choices=[("tshirt", "T-shirt sizes"), ("fibonacci", "Fibonacci")], default="tshirt", max_length=20
            ),
        ),
    ]
