# Generated by Django 4.1.7 on 2023-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker", "0002_alter_pokersession_deck"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokersession",
            name="reveal_count",
            field=models.IntegerField(default=0),
        ),
    ]
