# Generated by Django 4.1.7 on 2023-05-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker", "0003_pokersession_reveal_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokersession",
            name="auto_reveal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pokersession",
            name="deck",
            field=models.CharField(
                choices=[("tshirt", "T-shirt"), ("fibonacci", "Fibonacci")], default="tshirt", max_length=20
            ),
        ),
    ]
