# Generated by Django 4.1.7 on 2023-07-28 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poker", "0004_pokersession_auto_reveal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["pk"]},
        ),
    ]
