# Generated by Django 4.1.7 on 2023-09-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokersession",
            name="auto_reveal",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("event", models.CharField(max_length=100)),
                ("data", models.JSONField(default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="poker.pokersession"
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
