# Generated by Django 5.0.4 on 2024-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker", "0006_alter_pokersession_auto_reveal_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokersession",
            name="deck",
            field=models.CharField(
                choices=[("tshirt", "T-shirt"), ("fibonacci", "Fibonacci")], default="fibonacci", max_length=20
            ),
        ),
    ]
